name: Build and Deploy .NET 9 Web API

on:
  push:
    branches:
      - master 
env:
  AZURE_WEBAPP_NAME: bahadur2125
  DOTNET_VERSION: '9.0.x'
  BUILD_CONFIGURATION: Release

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore NuGet Packages
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Publish Project
        run: dotnet publish --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --output ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
